ALTER TABLE pick MODIFY COLUMN created TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00', ADD COLUMN `modified`    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ADD KEY modified (modified), ADD KEY created (created);

--

ALTER TABLE pick ADD COLUMN star_count INTEGER UNSIGNED NOT NULL DEFAULT 0 AFTER description;
